name: Executar Workflow de Build

on:
  push:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: log
        run: echo "Executando workflow de build"

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore github4womem/github4womem.csproj

      - name: Build project
        run: dotnet build github4womem/github4womem.csproj --configuration Release --no-restore